#!/bin/sh
set -eu

FILES=$(find Sources Tests -name '*.swift' ! -path '*/Fixtures/*' -print)

if [ -n "$FILES" ]; then
    echo "$FILES" | xargs swift format format --in-place --parallel
fi

swift build
swift test --parallel
