# .swiftlint.yml - Opinionated rules for g-cqd projects
# Aligned with SwiftProjectKit configuration

disabled_rules:
  - trailing_comma          # SwiftFormat handles this (--commas always)
  - nesting                 # Too restrictive for complex types
  - opening_brace           # SwiftFormat handles brace placement
  - blanket_disable_command # CLI commands legitimately need file-wide print statement disables

opt_in_rules:
  # Safety Rules (Critical)
  - force_unwrapping
  - implicitly_unwrapped_optional
  - unowned_variable_capture

  # Performance Rules
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - reduce_into
  - sorted_first_last

  # Code Quality Rules
  - array_init
  - discouraged_optional_boolean
  - explicit_init
  - fatal_error_message
  - identical_operands
  - joined_default_parameter
  - legacy_multiple
  - optional_enum_case_matching
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - unavailable_function
  - yoda_condition

  # Formatting Rules (complement SwiftFormat)
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - implicit_return
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - pattern_matching_keywords
  - sorted_imports
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

  # Access Control
  - extension_access_modifier
  - lower_acl_than_parent
  - private_action
  - private_outlet

  # Modern Swift
  - enum_case_associated_values_count
  - fallthrough
  - static_operator

  # Additional High-Value Rules
  - convenience_type
  - direct_return
  - discouraged_assert
  - file_name_no_space
  - prefer_self_in_static_references
  - shorthand_optional_binding
  - superfluous_disable_command

analyzer_rules:
  - unused_declaration
  - unused_import

excluded:
  - .build
  - .swiftpm
  - Package.swift
  - DerivedData
  - "*/Generated/*"
  - "**/Tests/Fixtures/*"
  # Plugins use print for CLI output - exclude from strict linting
  - Plugins
  # Test files have relaxed linting rules
  - Tests

# Naming Rules (relaxed for practical use)
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    # Loop indices
    - i
    - j
    - k
    # Coordinates
    - x
    - y
    - z
    # Common abbreviations
    - id
    - ok
    - to
    # Generic type parameters
    - T
    - U
    - V
    # Unused
    - _
    # Algorithm-specific (LSH bands/rows, hash values)
    - b
    - r
    - h
    # Math/Algorithm variables (length, count, etc.)
    - n
    - m
    - s
    - t
    - c
    - a
    - d
    - v
    - l

type_name:
  min_length:
    warning: 3
  max_length:
    warning: 50

# Line Length (aligned with SwiftFormat --maxwidth 120)
line_length:
  warning: 120
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

type_body_length:
  warning: 300

# Complexity (warnings only)
cyclomatic_complexity:
  warning: 15
  ignores_case_statements: true

function_parameter_count:
  warning: 5
  ignores_default_parameters: true

large_tuple:
  warning: 3

# File & Function Length (warnings only)
file_length:
  warning: 500
  ignore_comment_only_lines: true

function_body_length:
  warning: 50

# Custom Rules
custom_rules:
  no_print_statements:
    name: "No Print Statements"
    regex: '^\s*(print|debugPrint|dump)\s*\('
    match_kinds:
      - identifier
    message: "Remove print/debugPrint/dump before committing. Use a proper logging framework."
    severity: warning
    excluded:
      # CLI tools legitimately use print for user output
      - ".*/SwiftStaticAnalysisCLI/.*"
      - ".*/IndexStoreFallback\\.swift"
      - ".*/UnusedCodeDetector\\+IndexStore\\.swift"

  no_unchecked_sendable:
    name: "Avoid @unchecked Sendable"
    regex: '@unchecked\s+Sendable'
    message: "Use proper Sendable conformance or @preconcurrency import instead of @unchecked Sendable."
    severity: warning
    excluded:
      # Justified uses with proper thread-safety documentation:
      - ".*Protocols\\.swift"      # DefaultFileSystem wraps thread-safe FileManager
      - ".*MockDependencies\\.swift"  # Test mock with NSLock protection
      # Memory management types using raw pointers with manual synchronization
      - ".*/Memory/Arena\\.swift"
      - ".*/Memory/MemoryMappedFile\\.swift"
      - ".*/Memory/SoATokenStorage\\.swift"
      # Data flow analysis with actor-based isolation
      - ".*/DataFlow/SCCPAnalysis\\.swift"
      # Reachability graph uses internal locking
      - ".*/Reachability/ReachabilityGraph\\.swift"
      # IndexStore types with internal locking for thread-safety
      - ".*/IndexStore/IndexStoreReader\\.swift"
      - ".*/IndexStore/IndexStoreAnalyzer\\.swift"
      - ".*/IndexStore/IndexBasedDependencyGraph\\.swift"
      - ".*/IndexStore/IndexStoreFallback\\.swift"

  prefer_file_id:
    name: "Prefer #fileID"
    regex: '#file[^I]|#file$'
    message: "Use #fileID instead of #file for better performance."
    severity: warning

reporter: xcode
